export const Cars = [
  {
    id: 1,
    title: "Audi",
    model: "A7",
    engine: "Бензин",
    kpp: "Автомат",
    body: "Седан",
    year_from: "2010",
    old_price: "1200000",
    price: "2100000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: "Да",
  },
  {
    id: 2,
    title: "BMW",
    engine: "Бензин",
    model: "1 серия",
    kpp: "Механическая",
    body: "Седан",
    year_from: "2010",
    old_price: "1200000",
    price: "1100000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: "Да",
  },
  {
    id: 3,
    title: "BMW",
    engine: "Дизель",
    model: "2 серия",
    kpp: "Механическая",
    body: "Седан",
    year_from: "2010",
    old_price: "1200000",
    price: "900000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: "Да",
  },
  {
    id: 4,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Седан",
    year_from: "2011",
    old_price: "1200000",
    price: "1200000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: "Да",
  },
  {
    id: 5,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Седан",
    year_from: "2010",
    old_price: "1200000",
    price: "1200000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: "Да",
  },
  {
    id: 6,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Универсал",
    year_from: "2001",
    old_price: "1200000",
    price: "1200000",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: false,
  },
  {
    id: 7,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Минивэн",
    year_from: "2001",
    old_price: "10",
    price: "20",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: false,
  },
  {
    id: 8,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Седан",
    year_from: "2001",
    old_price: "30",
    price: "40",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: false,
  },
  {
    id: 9,
    title: "BMW",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Внедорожник",
    year_from: "2001",
    old_price: "30",
    price: "40",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: false,
  },
  {
    id: 10,
    title: "DW Hower",
    engine: "Дизель",
    model: "3 серия",
    kpp: "Механическая",
    body: "Хэтчбек",
    year_from: "2001",
    old_price: "30",
    price: "40",
    img: "/images/img1.webp",
    images: [
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
      "/images/img1.webp",
    ],
    mod: "1.8i CVT (160 л.с.)",
    mileage: "90000",
    drive: "Передний",
    color: "Серый",
    pts: "Оригинал",
    engine_volume: "1.8",
    wheel: "Левый",
    customs: "Растаможен",
    owners_by_pts: "1",
    auction: "Да",
    latest: "Да",
    promo: false,
  },
];
