//import { Cars } from "./cars";

export const ButtonCases = Object.freeze({
  CALLBACK: "Заказать звонок",
  ORDER: "Оставить заявку",
  CREDIT: "Рассчитать кредит",
  TRADE_IN: "Скидка по TRADE-IN",
  TRAID_IN_EXCHANGE: "Скидка при обмене TRADE-IN",
  CREDIT_ORDER: "Оформить заявку",
  INSTALLMENT: "Оформить в рассрочку",
  PODBOR: "Оформить заявку на подбор",
  VYKUP: "Оформить заявку на выкуп",
});

export const MenuItems = [
  {
    name: "Автомобили в наличии",
    link: "/catalog",
  },
  {
    name: "Заявка на автокредит",
    link: "/credit",
  },
  {
    name: "Обмен trade-in",
    link: "/trade-in",
  },
  {
    name: "Подбор автомобиля",
    link: "/podbor",
  },
  {
    name: "Срочный выкуп",
    link: "/vykup",
  },
  {
    name: "О компании",
    link: "/about",
  },
  {
    name: "Контакты",
    link: "/contacts",
  },
];

export const MainSliderSlides = [
  {
    id: 1,
    name: "Выгодный автокредит!",
    description: "Скидка до 100000 рублей!",
    content: [
      "Одобрение по паспорту и правам",
      "Первый взнос от 0%",
      "Широкий выбор кредитных программ",
    ],
    img: "/images/banner8.jpg",
    btnLink: "/credit",
    btnText: "Подробнее",
  },
  {
    id: 2,
    name: "Меняйся с выгодой!",
    description: "Скидка при обмене автомобиля до 50 000 ₽",
    content: [
      "В рассрочку или в кредит",
      "Оценка по рыночной стоимости",
      "Получите максимально возможную цену!",
    ],
    img: "/images/banner1.jpg",
    btnLink: "/trade-in",
    btnText: "Подробнее",
  },
  {
    id: 3,
    name: "Огромный выбор автомобилей с пробегом",
    description: "Осуществите свою мечту!",
    content: [
      "Только проверенные автомобили",
      "Юридическая чистота 100%",
      "Полная история всех автомобилей",
    ],
    img: "/images/banner3.jpg",
    btnLink: "/catalog",
    btnText: "Подробнее",
  },
];

export const SecondarySliderSlides = [
  {
    id: 1,
    name: "Огромный выбор авто в наличии",
    description: "Покупайте проверенные авто с пробегом в кредит",
    img: "/images/bg4.jpg",
    btnLink: "/catalog",
    btnText: "Подробнее",
  },
  {
    id: 2,
    name: "Срочный выкуп авто",
    description: "Бесплатная оценка и диагностика, рыночная цена 100%",
    img: "/images/bg5.webp",
    btnLink: "/vykup",
    btnText: "Подробнее",
  },
  {
    id: 3,
    name: "Лучший TRADE-IN в столице",
    description: "Обменяйте автомобиль с выгодой до 100 000 руб.",
    img: "/images/bg6.jpg",
    btnLink: "/trade-in",
    btnText: "Подробнее",
  },
];

export const ThirdSliderSlides = [
  /* {
    id: 1,
    name: "Седаны",
    description: "Классические городские автомобили",
    img: "/images/sedan.webp",
    btnLink: "/catalog?carBody=Седан",
    btnText: "Подробнее",
  },
  {
    id: 2,
    name: "Универсалы",
    description: "Для большой семьи",
    img: "/images/universal.webp",
    btnLink: "/catalog?carBody=Универсал",
    btnText: "Подробнее",
  },
  {
    id: 3,
    name: "Минивэны",
    description: "Лучшее для путешествий",
    img: "/images/miniven.webp",
    btnLink: "/catalog?carBody=Минивэн",
    btnText: "Подробнее",
  },
  {
    id: 4,
    name: "Хэтчбеки",
    description: "То что надо для города",
    img: "/images/hetch.webp",
    btnLink: "/catalog?carBody=Хэтчбек",
    btnText: "Подробнее",
  },
  {
    id: 5,
    name: "Внедорожники",
    description: "Когда размер имеет значение",
    img: "/images/out.webp",
    btnLink: "/catalog?carBody=Внедорожник",
    btnText: "Подробнее",
  }, */
  {
    id: 1,
    name: "Подбор автомобиля",
    description: "Подберем автомобиль на любой вкус",
    img: "/images/time-bg-1.jpg",
    btnLink: "/podbor",
    btnText: "Подробнее",
  },
  {
    id: 2,
    name: "Лучшие ставки по кредиту",
    description: "Широкие возможности",
    img: "/images/time-bg-2.jpg",
    btnLink: "/credit",
    btnText: "Подробнее",
  },
];

/**
 * @param {array} cars
 * @param {number} param
 * @return {object|null}
 */

export const getCar = (cars, param) => {
  const car = cars.find(({ id }) => id === param);
  return car != null ? car : null;
};

/**
 * @param {array} cars
 * @return {{array<object>} }
 */

export const getUniqueCarTitles = (cars) => {
  return [...new Set(cars.map(({ title }) => title))];
};

/**
 * @param {array} cars
 * @param {string} param
 * @return {Array}
 */
const mapAndUniqueFilters = (cars, param) => {
  return [...new Set(cars.map((key) => key[param]))];
};

//const filterNames = ["carTitles", "carModels", "carEngines", "carKpps", "carBodys", "carYearFroms"]

/**
 * @param {array} cars
 * @return {object}
 */
export const Filters = (cars) => {
  return {
    carTitles: mapAndUniqueFilters(cars, "title"),
    carModels: mapAndUniqueFilters(cars, "model"),
    carEngines: mapAndUniqueFilters(cars, "engine"),
    carKpps: mapAndUniqueFilters(cars, "kpp"),
    carBodys: mapAndUniqueFilters(cars, "body"),
    carYearFroms: mapAndUniqueFilters(cars, "year_from"),
  };
};

export const Queries = {
  carTitle: "",
  carModel: "",
  carEngine: "",
  carKpp: "",
  carBody: "",
  carYearFrom: "",
  carPrice: "",
  sort: "",
};

export const CarsTitles = [
  "Acura",
  "Audi",
  "BMW",
  "Brilliance",
  "Buick",
  "BYD",
  "Cadillac",
  "Changan",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Daewoo",
  "Datsun",
  "Dodge",
  "DongFeng",
  "DW Hower",
  "FAW",
  "Fiat",
  "Ford",
  "GEELY",
  "Great Wall",
  "Haima",
  "Haval",
  "Honda",
  "Hyundai",
  "Infiniti",
  "IVECO",
  "JAC",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lada",
  "Land Rover",
  "Lexus",
  "Lifan",
  "Luxgen",
  "Mazda",
  "Mercedes",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Ravon",
  "Renault",
  "Seat",
  "Skoda",
  "Ssang Yong",
  "Subaru",
  "Suzuki",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Vortex",
  "Zotye",
  "Газель",
  "ЗАЗ",
  "УАЗ",
];

/* export const CarsTitlesWithImgs = CarsTitles.reduce((acc, value) => {
  return {
    ...acc,
    [value.toUpperCase().replace(/ /g, "_")]: {
      title: value,
      img: "/images/acura_id60.png", count: 0
    },
  };
}, {}); */

export const CarsTitlesWithImgs = Object.freeze({
  ACURA: {
    title: "Acura",
    img: "/images/acura.png",
    count: 0,
  },
  AUDI: {
    title: "Audi",
    img: "/images/audi.png",
    count: 0,
  },
  BMW: {
    title: "BMW",
    img: "/images/bmw.png",
    count: 0,
  },
  BRILLIANCE: {
    title: "Brilliance",
    img: "/images/brilliance.png",
    count: 0,
  },
  BUICK: {
    title: "Buick",
    img: "/images/buick.png",
    count: 0,
  },
  BYD: {
    title: "BYD",
    img: "/images/byd.png",
    count: 0,
  },
  CADILLAC: {
    title: "Cadillac",
    img: "/images/cadillac.png",
    count: 0,
  },
  CHANGAN: {
    title: "Changan",
    img: "/images/changan.png",
    count: 0,
  },
  CHERY: {
    title: "Chery",
    img: "/images/chery.png",
    count: 0,
  },
  CHEVROLET: {
    title: "Chevrolet",
    img: "/images/chevrolet.png",
    count: 0,
  },
  CHRYSLER: {
    title: "Chrysler",
    img: "/images/chrysler.png",
    count: 0,
  },
  CITROEN: {
    title: "Citroen",
    img: "/images/citroen.png",
    count: 0,
  },
  DAEWOO: {
    title: "Daewoo",
    img: "/images/daewoo.png",
    count: 0,
  },
  DATSUN: {
    title: "Datsun",
    img: "/images/datsun.png",
    count: 0,
  },
  DODGE: {
    title: "Dodge",
    img: "/images/dodge.png",
    count: 0,
  },
  DONGFENG: {
    title: "DongFeng",
    img: "/images/dongfeng.png",
    count: 0,
  },
  DW_HOWER: {
    title: "DW Hower",
    img: "/images/dwhower.png",
    count: 0,
  },
  FAW: {
    title: "FAW",
    img: "/images/faw.png",
    count: 0,
  },
  FIAT: {
    title: "Fiat",
    img: "/images/fiat.png",
    count: 0,
  },
  FORD: {
    title: "Ford",
    img: "/images/ford.png",
    count: 0,
  },
  GEELY: {
    title: "GEELY",
    img: "/images/geely.png",
    count: 0,
  },
  GREAT_WALL: {
    title: "Great Wall",
    img: "/images/greatwall.png",
    count: 0,
  },
  HAIMA: {
    title: "Haima",
    img: "/images/haima.png",
    count: 0,
  },
  HAVAL: {
    title: "Haval",
    img: "/images/haval.png",
    count: 0,
  },
  HONDA: {
    title: "Honda",
    img: "/images/honda.png",
    count: 0,
  },
  HYUNDAI: {
    title: "Hyundai",
    img: "/images/hyundai.png",
    count: 0,
  },
  INFINITI: {
    title: "Infiniti",
    img: "/images/infiniti.png",
    count: 0,
  },
  IVECO: {
    title: "IVECO",
    img: "/images/iveco.png",
    count: 0,
  },
  JAC: {
    title: "JAC",
    img: "/images/jac.png",
    count: 0,
  },
  JAGUAR: {
    title: "Jaguar",
    img: "/images/jaguar.png",
    count: 0,
  },
  JEEP: {
    title: "Jeep",
    img: "/images/jeep.png",
    count: 0,
  },
  KIA: {
    title: "Kia",
    img: "/images/kia.png",
    count: 0,
  },
  LADA: {
    title: "Lada",
    img: "/images/lada.png",
    count: 0,
  },
  LAND_ROVER: {
    title: "Land Rover",
    img: "/images/landrover.png",
    count: 0,
  },
  LEXUS: {
    title: "Lexus",
    img: "/images/lexus.png",
    count: 0,
  },
  LIFAN: {
    title: "Lifan",
    img: "/images/lifan.png",
    count: 0,
  },
  LUXGEN: {
    title: "Luxgen ",
    img: "/images/luxgen.png",
    count: 0,
  },
  MAZDA: {
    title: "Mazda",
    img: "/images/mazda.png",
    count: 0,
  },
  MERCEDES: {
    title: "Mercedes",
    img: "/images/mercedes.png",
    count: 0,
  },
  MINI: {
    title: "MINI",
    img: "/images/mini.png",
    count: 0,
  },
  MITSUBISHI: {
    title: "Mitsubishi",
    img: "/images/mitsubishi.png",
    count: 0,
  },
  NISSAN: {
    title: "Nissan",
    img: "/images/nissan.png",
    count: 0,
  },
  OPEL: {
    title: "Opel",
    img: "/images/opel.png",
    count: 0,
  },
  PEUGEOT: {
    title: "Peugeot",
    img: "/images/peugeot.png",
    count: 0,
  },
  PORSCHE: {
    title: "Porsche",
    img: "/images/porsche.png",
    count: 0,
  },
  RAVON: {
    title: "Ravon",
    img: "/images/ravon.png",
    count: 0,
  },
  RENAULT: {
    title: "Renault",
    img: "/images/renault.png",
    count: 0,
  },
  SEAT: {
    title: "Seat",
    img: "/images/seat.png",
    count: 0,
  },
  SKODA: {
    title: "Skoda",
    img: "/images/skoda.png",
    count: 0,
  },
  SSANG_YONG: {
    title: "Ssang Yong",
    img: "/images/ssangyong.png",
    count: 0,
  },
  SUBARU: {
    title: "Subaru",
    img: "/images/subaru.png",
    count: 0,
  },
  SUZUKI: {
    title: "Suzuki",
    img: "/images/suzuki.png",
    count: 0,
  },
  TOYOTA: {
    title: "Toyota",
    img: "/images/toyota.png",
    count: 0,
  },
  VOLKSWAGEN: {
    title: "Volkswagen",
    img: "/images/volkswagen.png",
    count: 0,
  },
  VOLVO: {
    title: "Volvo",
    img: "/images/volvo.png",
    count: 0,
  },
  VORTEX: {
    title: "Vortex",
    img: "/images/vortex.png",
    count: 0,
  },
  ZOTYE: {
    title: "Zotye",
    img: "/images/zotye.png",
    count: 0,
  },
  ГАЗЕЛЬ: {
    title: "Газель",
    img: "/images/gaz.png",
    count: 0,
  },
  ЗАЗ: {
    title: "ЗАЗ",
    img: "/images/zaz.png",
    count: 0,
  },
  УАЗ: {
    title: "УАЗ",
    img: "/images/uaz.png",
    count: 0,
  },
});

export const Months = [
  "Январе",
  "Феврале",
  "Марте",
  "Апреле",
  "Мае",
  "Июне",
  "Июле",
  "Августе",
  "Сентябре",
  "Октябре",
  "Ноябре",
  "Декабре",
];

export const MonthsOther = [
  "Января",
  "Февраля",
  "Марта",
  "Апреля",
  "Мая",
  "Июня",
  "Июля",
  "Августа",
  "Сентября",
  "Октября",
  "Ноября",
  "Декабря",
];

export const SITE_DOMEN = "https://vegamotormsk.ru/";
export const SERVER_HOST = "http://localhost:3333/";

export const CarsBodys = Object.freeze({
  BORTOVOY_GRUZOVIK: "Бортовой грузовик",
  VNEDOROZHNIK: "Внедорожник",
  IZOTERM: "Изотермический кузов",
  KABRIOLET: "Кабриолет",
  KOMPACT_VEN: "Компактвэн",
  KUPE: "Купэ",
  LIMUZIN: "Лимузин",
  LIFTBEK: "Лифтбэк",
  MIKROAVTOBUS: "Микроавтобус",
  MINIVEN: "Минивэн",
  PICKUP: "Пикап",
  PROMTOVARNYI_AVTOFURGON: "Промтоварный автофургон",
  REFRIZHERATOR: "Рефрижератор",
  SEDAN: "Седан",
  UNIVERSAL: "Универсал",
  FURGON: "Фургон",
  HATCHBACK: "Хэтчбэк",
  FURGON_METAL: "Цельнометаллический фургон",
});

export const CarBodysValues = Object.values(CarsBodys);

export const CarsEngines = Object.freeze({
  BENZIN: "Бензин",
  DIZEL: "Дизель",
  GAZ: "Газ",
  GAZ_BENZIN: "Газ/Бензин",
  GIBRID: "Гибрид",
});

export const CarsEnginesValues = Object.values(CarsEngines);

export const CarsDrives = Object.freeze({
  PEREDNIY: "Передний",
  ZADNIY: "Задний",
  POLNIY: "Полный",
});

export const CarsDrivesValues = Object.values(CarsDrives);

export const CarsKpps = Object.freeze({
  AUTOMAT: "Автомат",
  AUTOMAT_VARIATOR: "Автомат вариатор",
  AUTOMAT_ROBOT: "Автомат робот",
  HAND: "Механическая",
});

export const CarsKppsValues = Object.values(CarsKpps);

export const CarsWheels = Object.freeze({
  RIGHT: "Правый",
  LEFT: "Левый",
});

export const CarsWheelsValues = Object.values(CarsWheels);

export const fullCarsModels = Object.freeze({
  "Land Rover": [
    "Discovery",
    "FREELANDER",
    "Freelander",
    "Freelander II Рестайлинг 2",
    "Range Rover Evoque I",
    "Range Rover Evoque I Рестайлинг",
  ],
  Toyota: [
    "Camry VII (XV50) Рестайлинг 2",
    "Camry",
    "Rav4",
    "Corolla",
    "Camry",
    "Land Cruiser 200",
    "Camry VII (XV50)",
    "Corolla",
    "Corolla",
    "Corolla XI (E160, E170)",
    "RAV4 III (XA30) Рестайлинг",
    "Camry VII (XV50) Рестайлинг",
    "Camry VII (XV50)",
    "Corolla X (E140, E150) Рестайлинг",
    "RAV4 IV (XA40) Рестайлинг",
    "Camry VII (XV50) Рестайлинг",
    "Camry VIII (XV70)",
  ],
  Hyundai: [
    "Solaris II",
    "H-1",
    "ix35",
    "ix35",
    "ix35",
    "Solaris II",
    "Solaris ll",
    "Ix35",
    "ix35",
    "Creta",
    "Ix35",
    "Creta",
    "Solaris II",
    "Creta",
    "Creta I",
    "Creta I",
    "Creta I",
    "Creta I Рестайлинг",
    "Elantra VI (AD) Рестайлинг",
    "H-1 II Рестайлинг 2",
    "ix35 I Рестайлинг",
    "ix35 I",
    "ix35 I",
    "ix35 I",
    "Santa Fe III Рестайлинг",
    "Solaris I Рестайлинг",
    "Solaris I Рестайлинг",
    "Solaris I Рестайлинг",
    "Solaris I",
    "Solaris II",
    "Solaris I",
    "Solaris II Рестайлинг",
    "Santa Fe IV",
    "Solaris I Рестайлинг",
    "ix55",
    "Santa Fe II Рестайлинг",
    "Solaris II Рестайлинг",
    " Creta",
    "Solaris I Рестайлинг",
    "Solaris I Рестайлинг",
    "Creta",
    "Solaris I",
    "Creta",
    "Grand Starex I Рестайлинг",
    "ix35",
    "Solaris I",
    "Creta I Рестайлинг",
    "Elantra V (MD) Рестайлинг",
    "Solaris",
    "Santa Fe III",
    "Creta ",
    "Solaris I Рестайлинг",
    "Creta II",
    "Creta",
    "Sonata VIII (DN8)",
    "Creta",
    "Creta",
    "Solaris II Рестайлинг",
    "H-1 II Рестайлинг",
    "Elantra VI (AD)",
    "Santa Fe III",
    "H-1 II Рестайлинг 2",
    "ix35 I Рестайлинг",
  ],
  Renault: [
    "Logan Stepway  II Рестайлинг",
    "Duster",
    "Logan",
    "Megane",
    "Kaptur",
    "Duster",
    "Kaptur",
    "Logan Stepway II Рестайлинг",
    "Logan Stepway II Рестайлинг",
    "Logan II Рестайлинг",
    "Logan II Рестайлинг",
    "Logan II Рестайлинг",
    "Sandero Stepway II",
    "Sandero Stepway II",
    "Sandero Stepway II",
    "Kaptur",
    "Duster I Рестайлинг",
    "Logan Stepway II Рестайлинг",
    "Sandero",
    "Logan",
    "Logan II",
    "Stepway II Рестайлинг",
    "Logan Stepway II Рестайлинг",
    "Logan II",
    "Logan I Рестайлинг",
    "Duster I Рестайлинг",
    "Sandero Stepway II",
    "Logan I Рестайлинг",
    "Arkana I",
  ],
  Chevrolet: [
    "Cruze",
    "Cruze",
    "Cruze",
    "Captiva",
    "Captiva",
    "Aveo",
    "Cruze",
    "Lacetti",
    "Niva I Рестайлинг",
    "Cruze",
    "Cruze I Рестайлинг",
    "Cruze I Рестайлинг",
    "Cruze I Рестайлинг",
  ],
  Ford: [
    "Focus",
    "Focus",
    "Focus",
    "EcoSport",
    "EcoSport",
    "Mondeo",
    "EcoSport",
    "EcoSport",
    "Focus III",
    "Focus II Рестайлинг",
    "Focus II Рестайлинг",
    "Kuga",
    "Kuga II",
    "Mondeo IV Рестайлинг",
    "Mondeo V",
    "Focus III",
    "II Рестайлинг",
    "Mondeo IV Рестайлинг",
    "Focus II Рестайлинг",
    "Focus II Рестайлинг",
    "Kuga II",
    "Kuga II",
    "S-MAX",
    "III Рестайлинг",
    "Mondeo IV Рестайлинг",
    "Kuga II",
    "EcoSport",
    "Focus III",
    "Focus II Рестайлинг",
    "Kuga II",
    "Mondeo V",
    "Mondeo V",
  ],
  "Great Wall": ["Hover", "Hover H5"],
  Kia: [
    "Rio",
    "Rio X-Line",
    "Rio X-Line",
    "Rio X-Line",
    "Rio IV",
    "Sportage",
    "Sportage",
    "Rio X-Line",
    "Rio",
    "Rio",
    "Ceed",
    "Soul",
    "Optima",
    "K5 III",
    "Ceed I",
    "Ceed II",
    "Ceed II",
    "Ceed II",
    "Cerato III Рестайлинг (Classic)",
    "Cerato IV",
    "Optima IV Рестайлинг",
    "Optima IV Рестайлинг",
    "Optima IV Рестайлинг",
    "Optima IV Рестайлинг",
    "Optima III Рестайлинг",
    "Optima IV",
    "Optima IV",
    "Rio X-Line IV",
    "Rio X-Line IV",
    "Rio X-Line IV",
    "Rio III Рестайлинг",
    "Rio IV",
    "Rio IV Рестайлинг",
    "Sorento II Рестайлинг",
    "Sorento II Рестайлинг",
    "Sportage II Рестайлинг",
    "Sportage III",
    "Rio IV",
    "Rio X-Line IV",
    "Sorento II",
    "K5 III",
    "Rio X-Line IV",
    "Rio X-Line IV",
    "Rio X-Line IV",
    "Rio III",
    "Ceed II",
    "Sportage II",
    "Sportage III",
    "K5 III",
    "Rio X-Line IV",
    "Rio X-Line IV",
    "Rio IV Рестайлинг",
    "Rio X-Line IV",
    "Sportage IV",
    "Sportage IV",
    "Rio IV",
    "Ceed III",
    "Sportage IV Рестайлинг",
    "Rio IV",
    "Rio X-Line",
    "Sorento II Рестайлинг",
    "Rio IV",
  ],
  Skoda: [
    "Octavia",
    "Octavia",
    "Octavia",
    "Octavia",
    "Octavia",
    "Octavia",
    "Superb",
    "Yeti",
    "Yeti ",
    "YETI",
    "Octavia II (A5) Рестайлинг",
    "Octavia III (A7) Рестайлинг",
    "Octavia II (A5) Рестайлинг",
    "Octavia III (A7)",
    "Octavia III (A7) Рестайлинг",
    "Octavia III (A7) Рестайлинг",
    "Octavia III (A7) Рестайлинг",
    "Rapid",
    "Rapid I Рестайлинг",
    "Rapid I Рестайлинг",
    "Yeti I Рестайлинг",
    "Yeti",
    "Yeti I Рестайлинг",
    "Superb II Рестайлинг",
    "Octavia III (A7)",
    "Octavia III (A7) Рестайлинг",
    "Yeti",
    "Octavia III (A7) Рестайлинг",
    "Octavia III (A7) Рестайлинг",
    "Octavia III (A7) Рестайлинг",
    "Octavia III (A7)",
  ],
  Volkswagen: [
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Touareg",
    "Passat B8",
    "Tiguan",
    "Tiguan",
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Polo",
    "Amarok",
    "Arteon",
    "Golf VII",
    "Jetta VI Рестайлинг",
    "Passat B7",
    "Passat B6",
    "V Рестайлинг",
    "Tiguan I Рестайлинг",
    "Polo V Рестайлинг",
    "Polo V Рестайлинг",
    "Passat B8",
    "Polo V Рестайлинг",
    "Polo V",
    "Polo V",
    "Tiguan I Рестайлинг",
    "Touareg I Рестайлинг",
    "Tiguan I Рестайлинг",
    "Caddy III",
    "Tiguan I Рестайлинг",
    "Passat B8",
    "Jetta VI",
    "Jetta VI Рестайлинг",
    "Polo V Рестайлинг",
    "Passat B7",
    "Polo VI Рестайлинг",
    "Polo VI Рестайлинг",
    "Passat B8",
  ],
  Lada: [
    "Largus",
    "2131 (4x4)",
    "Granta I Рестайлинг",
    "Largus Cross I",
    "Largus Cross I",
    "Largus Cross I",
    "Largus I",
    "2121 (4x4) Urban",
    "2121 (4x4) I Рестайлинг",
    "ВАЗ 2131 (4x4)",
    "Largus",
    "2121 (4x4) I Рестайлинг ",
    "2121 (4x4) I Рестайлинг ",
    "Granta",
    "Granta",
    "Granta",
    "Vesta Cross I",
    "Vesta I",
  ],
  Nissan: [
    "Juke",
    "Juke",
    "Qashqai",
    "Juke I",
    "Juke I",
    "Qashqai I Рестайлинг",
    "Qashqai II",
    "Almera III (G15)",
    "Qashqai II",
    "Qashqai II",
    "Qashqai II",
    "X-Trail II",
    "Juke",
    "Almera II (N16) Рестайлинг",
    "Qashqai I Рестайлинг",
    "Qashqai II",
    "X-Trail II Рестайлинг",
    "Juke",
    "Qashqai+2",
    "Pathfinder IV",
  ],
  Opel: [
    "Astra",
    "Mokka",
    "Astra",
    "Astra GTC",
    "Meriva A",
    "Astra J Рестайлинг",
    "Insignia I",
    "Antara",
    "Zafira B Рестайлинг",
    "Vectra C Рестайлинг",
    "Corsa D",
  ],
  Suzuki: [
    "SX4",
    "Vitara",
    "Vitara",
    "SX4 I (Classic) Рестайлинг",
    "Grand Vitara III Рестайлинг",
    "Grand Vitara III Рестайлинг",
  ],
  Mitsubishi: [
    "ASX",
    "Pajero sport III Рестайлинг",
    "ASX",
    "Outlander",
    "Outlander",
    "Outlander",
    "Outlander",
    "Lancer X Рестайлинг",
    "Lancer IX Рестайлинг",
    "Outlander II Рестайлинг",
    "Outlander II Рестайлинг",
  ],
  Citroen: ["C4"],
  "Ssang Yong": ["Actyon", "Actyon II"],
  Haval: ["H6"],
  Mazda: [
    "6",
    "CX-7 I Рестайлинг",
    "3 I (BK) Рестайлинг",
    "3",
    "3 I (BK) Рестайлинг",
    "CX-7 I Рестайлинг",
    "6 III (GJ) Рестайлинг",
  ],
  Mercedes: ["CLA", "M-Класс II (W164) Рестайлинг"],
  Audi: [
    "A4 IV (B8) Рестайлинг",
    "Q5 I (8R)",
    "Q7 II (4M)",
    "Q5 I (8R)",
    "A6 IV (C7)",
    "A6 IV (C7) Рестайлинг",
    "A7",
    "Q3",
    "Q5 I (8R) Рестайлинг",
    "A5 I (8T) Рестайлинг",
  ],
  BMW: [
    "5 (F10/F11/F07) Рестайлинг",
    "X1 I (E84) Рестайлинг",
    "5 серии VII (G30/G31)",
    "7 серии Long 725Ld VI (G11/G12)",
    "X3 II (F25) Рестайлинг",
    "5 серии 520d VII",
    "X6 I (E71)",
  ],
  FAW: ["Oley", "Besturn X80"],
  Honda: ["Civic VIII", "Pilot II"],
  Lifan: ["X60 I Рестайлинг 2", "Myway"],
  Subaru: ["Forester III", "Forester III", "Forester V"],
  Peugeot: ["308", "3008", "3008"],
  Datsun: ["on-DO"],
  Brilliance: ["V5"],
  JAC: ["S7"],
  Zotye: ["T600"],
  Volvo: ["S60 II", "S60 II Рестайлинг", "XC70 II"],
  Jeep: ["Compass II", "Grand Cherokee IV (WK2)"],
  GEELY: ["Coolray", "Coolray"],
  Chery: ["Tiggo 8 Pro"],
});
